import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import ModalSelect from './components/ModalSelect';
import Navbar from './components/Navbar';
import { SelectProvider } from './context/SelectContext';
import { CartProvider } from './context/CartContext';
import { WishlistProvider } from './context/WishlistContext';
import { Toaster } from 'react-hot-toast';
import BottomNav from './components/Navbar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster position='top-center' />{' '}
        <SelectProvider>
          <CartProvider>
            <WishlistProvider>
              <Navbar />

              <ModalSelect />
              <div className='mt-40'>{children}</div>
            </WishlistProvider>
          </CartProvider>
        </SelectProvider>
      </body>
    </html>
  );
}
